title: "Kirutiga Srikanda Prabanna Balan"
description: "Electrochemistry • Materials • Intelligent Systems"
url: "" 
baseurl: "" 

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-sitemap

author:
  name   : "Kirutiga Balan"
  avatar : "/assets/images/profile.jpg"
  bio    : "Research engineer with dual MS (Materials Science & Aerospace, UT Austin). Specializing in electrochemistry, microfluidics, and modeling."
  location: "United States"
  email  : "krithika151997@gmail.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/kirutiga-balan"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/your-handle"
    - label: "Resume"
      icon: "fas fa-file-pdf"
      url: "/assets/resume.pdf"

nav:
  - title: "About"
    url: /about/
  - title: "Experience"
    url: /experience/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

markdown: kramdown
highlighter: rouge
